name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build Go application
      run: go build -o go-web-app

    - name: Run Go tests
      run: go test ./...
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/private-navyaportfolio-golang:${{github.run_id}}

  update-helm:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update Helm chart image tag
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-application-chart/values.yaml

    - name: Commit and push Helm chart changes
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.USERNAME }}"
        git add helm/go-web-application-chart/values.yaml
        git commit -m "Update Docker image tag in Helm chart to ${{github.run_id}}"
        git push

  notify:
    runs-on: ubuntu-latest
    needs: [build, lint, docker, update-helm]
    if: always()  # Run this job regardless of the outcome of other jobs
    steps:
    - name: Send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com  # Change this to your SMTP server
        server_port: 465
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: GitHub Actions CI/CD Pipeline - ${{ github.workflow }} - ${{ job.status }}
        to: ${{ secrets.EMAIL }}
        from: GitHub Actions <${{ secrets.EMAIL }}>
        body: |
          CI/CD Pipeline Summary for ${{ github.repository }}:
          
          Build Status: ${{ needs.build.result }}
          Lint Status: ${{ needs.lint.result }}
          Docker Build & Push Status: ${{ needs.docker.result }}
          Helm Update Status: ${{ needs.update-helm.result }}
          
          For details, check the [GitHub Actions log](${{
            github.server_url
          }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
